export type Product = { id:string; slug:string; name:string; brand:string; price:number; oldPrice?:number; image:string; category:string; type:string; concentration:string; size:string; notes:string[]; description:string; stock:number; bestSeller?:boolean; featured?:boolean };
export const categories = [
  {slug:'fresh', name:'Fresh Collection', subtitle:'Cítricos y luminosos', image:'/images/collections/fresh-collection.jpg'},
  {slug:'daily', name:'Daily Collection', subtitle:'Elegancia cotidiana', image:'/images/collections/daily-collection.jpg'},
  {slug:'night-out', name:'Night Out Collection', subtitle:'Para dejar huella', image:'/images/collections/night-out-collection.jpg'},
  {slug:'arabian', name:'Arabian Collection', subtitle:'Intensidad oriental', image:'/images/collections/arabian-collection.jpg'}
];
export const products: Product[] = [
 {id:'1',slug:'aventus',name:'Aventus',brand:'Creed',price:690000,image:'https://images.unsplash.com/photo-1594035910387-fea47794261f?auto=format&fit=crop&w=800&q=85',category:'fresh',type:'Designer',concentration:'Eau de Parfum',size:'100 ml',notes:['Piña','Abedul','Almizcle'],description:'Una firma vibrante y sofisticada que combina fruta luminosa con maderas nobles.',stock:8,bestSeller:true,featured:true},
 {id:'2',slug:'bleu-de-nuit',name:'Bleu de Nuit',brand:'Maison G',price:650000,image:'https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=800&q=85',category:'daily',type:'Designer',concentration:'Parfum',size:'100 ml',notes:['Pomelo','Incienso','Cedro'],description:'Un aroma limpio y profundo, construido para acompañar cada día.',stock:13,bestSeller:true},
 {id:'3',slug:'oud-wood',name:'Oud Wood',brand:'Atelier No. 8',price:685000,image:'https://images.unsplash.com/photo-1563170351-be82bc888aa4?auto=format&fit=crop&w=800&q=85',category:'night-out',type:'Niche',concentration:'Eau de Parfum',size:'50 ml',notes:['Oud','Cardamomo','Vainilla'],description:'Maderas cálidas y especias suaves en un acorde de presencia impecable.',stock:6,bestSeller:true},
 {id:'4',slug:'ambre-royal',name:'Ambre Royal',brand:'Maison d’Or',price:1250000,image:'https://images.unsplash.com/photo-1595425970377-c9703cf48b6d?auto=format&fit=crop&w=800&q=85',category:'arabian',type:'Arabian',concentration:'Extrait de Parfum',size:'70 ml',notes:['Azafrán','Ámbar','Resinas'],description:'Un extracto opulento de sillage envolvente y acabado aterciopelado.',stock:3,bestSeller:true,featured:true},
 {id:'5',slug:'sauvage-elixir',name:'Sauvage Elixir',brand:'Dior',price:680000,image:'https://images.unsplash.com/photo-1610461888750-10bfc601b874?auto=format&fit=crop&w=800&q=85',category:'night-out',type:'Designer',concentration:'Parfum',size:'60 ml',notes:['Lavanda','Regaliz','Maderas'],description:'Contrastes aromáticos y especiados para las noches que cuentan.',stock:10,bestSeller:true},
 {id:'6',slug:'ysl-y-edp',name:'Y Eau de Parfum',brand:'Yves Saint Laurent',price:595000,image:'https://images.unsplash.com/photo-1523293182086-7651a899d37f?auto=format&fit=crop&w=800&q=85',category:'daily',type:'Designer',concentration:'Eau de Parfum',size:'100 ml',notes:['Manzana','Salvia','Haba tonka'],description:'Fresco, moderno y con una base cálida de gran versatilidad.',stock:12,bestSeller:true},
 {id:'7',slug:'citrus-atelier',name:'Citrus Atelier',brand:'Lumière',price:420000,image:'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?auto=format&fit=crop&w=800&q=85',category:'fresh',type:'Niche',concentration:'Eau de Toilette',size:'75 ml',notes:['Bergamota','Neroli','Vetiver'],description:'La sensación de una mañana mediterránea embotellada.',stock:16,featured:true}
];
export const formatCOP=(value:number)=>new Intl.NumberFormat('es-CO',{style:'currency',currency:'COP',maximumFractionDigits:0}).format(value);
